spring:
  cloud:
    gateway:
      predicate:
        After:
          enabled: false    #不加载 spring cloud  默认predicate
        weight:
          enabled: false
      routes:
        - id: test_router
          uri: http://127.0.0.1:9090
          predicates:
            - Path=/api/v1/{segment}

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'
