spring:
  cloud:
    gateway:
      predicate:
        After:
          enabled: false    #不加载 spring cloud  默认predicate
        weight:
          enabled: false
      routes:
        - id: test_router
          uri: https://www.jianshu.com/
          predicates:
            - Method=GET,POST
            - Path=/p/{segment},/u/{segment}

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'
